CREATE VIEW DetallesReservas AS
SELECT r.ID_RESERVA, r.FECHA_RESERVA, c.NOMAPE AS NOMBRE_CLIENTE, p.PLATO, b.NOMBEBIDA
FROM RESERVA r
JOIN CLIENTE c ON r.ID_CLIENTE = c.ID_CLIENTE
JOIN PLATO p ON r.ID_PLATO = p.ID_PLATO
JOIN BEBIDA b ON r.ID_BEBIDA = b.ID_BEBIDA;
